#Chrome or Firefox or IE or Edge
browser = Chrome
#true or false
headless = false
#true or false
seleniumGrid = false
hubURL = http://localhost:4444/
#test or staging
environment = test
#environment = ${environment}
#URLs
webTestURL = https://www.telerik.com/support/demos/